# Generated by Django 4.2.4 on 2023-08-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='enlace',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='categoria',
            field=models.CharField(choices=[('Acción', 'Acción'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Fantasía', 'Fantasía')], max_length=20),
        ),
    ]
