# Generated by Django 4.2.4 on 2023-08-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('argumento', models.CharField(max_length=800)),
                ('director', models.CharField(max_length=20)),
                ('duracion', models.IntegerField(null=True)),
                ('num_capitulos', models.IntegerField(null=True)),
                ('num_temporadas', models.IntegerField(null=True)),
                ('anio_estreno', models.IntegerField(null=True)),
                ('categoria', models.CharField(choices=[('Acción', 'Acción'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Fantasía', 'Fantasía')], max_length=20)),
                ('favorito', models.BooleanField(default=False)),
                ('vista', models.BooleanField(default=False)),
                ('imagen', models.ImageField(upload_to='series')),
                ('enlace', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'serie',
                'verbose_name_plural': 'series',
            },
        ),
    ]
