# Generated by Django 4.2.4 on 2023-08-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='director',
        ),
        migrations.AddField(
            model_name='serie',
            name='creador',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
